### ISSUE TITLE
[Help Wanted] Is the left part a ListView?

### ISSUE THREAD

**Issue by ShannonZ** [Abel13/AnimatedMenu1#2]
[![UI.png](https://i.loli.net/2019/04/29/5cc6602d5dd9f.png)](https://i.loli.net/2019/04/29/5cc6602d5dd9f.png)
Is the left part a ListView or DataGrid?
Does the polygon belong to the item selected highlighted style? 
If yes, why could the area of the polygon exceed the border of the container?

Is it possible to make this kind of UI using C#/Xaml?

P.S.: I‘ve subscribed your youtube channel and learned a lot from your videos. Thanks for your kindly sharing.

**Comment by Abel13** [comment]
Hi, I think it is possible in a listview.. you can do this style on your item I think... I'll try to do some video like that
